### ISSUE TITLE
Problem with data URI images

### ISSUE THREAD

**Issue by iangilman** [openseadragon/browser-extension#11]
If you go to a Google image search, e.g.: 

https://www.google.com/search?q=space+station&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMI2PLP45_yyAIVQ91jCh2bfgMg&biw=1543&bih=1269

...and right click on one of the thumbnails (which are data URI images) and select OpenSeadragonizer, it breaks the extension. In Chrome you get a blank screen and in Firefox you get a "can't find requested server" error. 

I don't know that we need to support data URI's at all, but maybe we should fail gracefully.

**Comment by avandecreme** [comment]
I just checked, data URI are supported by the new ImageTileSource. :)

Also, on master, Firefox now behave like Chrome.
To improve the error, maybe we should listen for an OpenSeadragon event but I am not sure which one.

**Comment by iangilman** [comment]
Cool, maybe we should test again once ImageTileSource is integrated in. 

As for what event to listen for, looks like you want Viewer's `tile-load-failed` event (since the tile source itself will load fine, but the tile will fail).
