### ISSUE TITLE
For publish, use the site's copy of OSD? 

### ISSUE THREAD

**Issue by iangilman** [openseadragon/browser-extension#14]
Right now `grunt publish` copies over the browser-extension version of OSD, when the site already has a version. Maybe we should point to the same one? On the other hand, maybe it's better to keep them separate so we know the extension is using it's compatible with (and to avoid more fiddly Grunt work). Anyway, thought I'd mention it.

**Comment by avandecreme** [comment]
I think it is safer to use it own copy in case the 2 are not evolving at the same speed.
Also I think it would be nice to use npm to pull openseadragon in this repository (whenever OSD will be available on npm).

**Comment by iangilman** [comment]
Cool, works for me.
