### ISSUE TITLE
Add build to the publish task.

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/browser-extension#15]
Cf: https://github.com/openseadragon/browser-extension/commit/2a6b771eff9b5ae9f574656bff804674b3886e9f#diff-35b4a816e0441e6a375cd925af50752cL134

**Comment by iangilman** [comment]
I guess it's not strictly necessary as you say, since the publish doesn't depend on the build results (that was my misunderstanding), but still probably a good check.

**Comment by avandecreme** [comment]
Fixed by https://github.com/openseadragon/browser-extension/commit/b6bb937a72ea57ad230e8c8459eb90e9bbab950b
