### ISSUE TITLE
Spinner while loading

### ISSUE THREAD

**Issue by iangilman** [openseadragon/browser-extension#18]
Some images take a little while to load, and while it's loading there is no Seadragon UI. Maybe we could put up a spinner or a "loading" message to indicate there is more to come.

**Comment by julmot** [comment]
Should this message still be available? I can't see it during my image is loading.

**Comment by avandecreme** [comment]
Yes it should.
What browser are you using?

**Comment by julmot** [comment]
Firefox 57 on Windows 10

**Comment by julmot** [comment]
Do you need to generate some specific HTML that the message appears?

**Comment by iangilman** [comment]
@julmot You are talking about the browser extension (or the OpenSeadragonizer page), correct (not OpenSeadragon itself)? I can see the spinner here:

http://openseadragon.github.io/openseadragonizer/?img=https://static.pexels.com/photos/110854/pexels-photo-110854.jpeg

Can you not?

**Comment by avandecreme** [comment]
I just checked, I do have the spinner in the Firefox extension as well.
