### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by iangilman** [openseadragon/browser-extension#2]
Anyone want to jump in and make that happen?

**Comment by avandecreme** [comment]
https://github.com/openseadragon/browser-extension/commit/11e015e6c58d415acb5d1821ecfee64179d383d6 :)

Still some work to do about the packaging.

**Comment by iangilman** [comment]
Nice! Please add instructions to the README as well. 

What's involved in adding it to their web store?

**Comment by avandecreme** [comment]
Published: https://addons.mozilla.org/en-US/firefox/addon/openseadragonizer/

However there is some sort of review process. I selected "Preliminary review" for now. It should be faster but has some limitations: https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews
We can make a full review later.

**Comment by avandecreme** [comment]
I did not forget the README, I hope to do that later this weekend. :)

**Comment by avandecreme** [comment]
And the extension has been accepted with the following comment:
>Please don't include the same library, normal and minified.

Easy enough to fix :)

I also updated the readme.

**Comment by iangilman** [comment]
Everything looks beautiful! 

I like the addition of the context menu shot in the screenshots. Might be good to give a mention to the context menu in the textual description as well.

**Comment by avandecreme** [comment]
Version 1.1.0 awaiting review.
I will open a new issue if there is any problem.
