### ISSUE TITLE
Update OSD

### ISSUE THREAD

**Issue by avandecreme** [openseadragon/browser-extension#20]
Now that 2.2.0 is out.

**Comment by avandecreme** [comment]
Done. I guess we could publish a version 1.1.1.
A "go home" bug which was affecting this plugin has been fixed in OSD.

**Comment by iangilman** [comment]
Sounds good... what's involved in publishing a new version?

Also, do we need to publish this to openseadragon.github.io as well, or does it just pick up the OSD that's there?

**Comment by avandecreme** [comment]
Sorry for the late answer on this.
I made some more changes. See PR #21 
I deployed to both the Mozilla and Chrome stores.
It would be nice if you could publish to openseadragon.github.io (see the last section of the Readme for the steps).

**Comment by iangilman** [comment]
Excellent... deployed!

**Comment by avandecreme** [comment]
Thanks!
