### ISSUE TITLE
Webpage is blank

### ISSUE THREAD

**Issue by brentkendall** [openseadragon/browser-extension#23]
I thought I could still use OpenSeadragon with an image created in the Deep Zoom Composer, only I can’t get it to work.  I followed the OpenSeadragon steps, but I just get a blank browser page.  My index.html file is pretty-much like below:

<div id="openseadragon1" style="width: 800px; height: 600px;"></div>
<script src="/openseadragon/openseadragon.min.js"></script>
<script type="text/javascript">
    var viewer = OpenSeadragon({
        id: "openseadragon1",
        prefixUrl: "/openseadragon/images/",
        tileSources: "/myImages/dzc_output.xml"
    });
</script>

I just get a blank page on Chrome, Firefox, IE11, or Edge (I really need this to work only on Edge).

Do I have to parse the XML per this posting:  https://github.com/openseadragon/site-build/issues/5#issuecomment-48363164?  That doesn’t seem right, and others have had success without going so far?

Any help is appreciated

**Comment by avandecreme** [comment]
Hello,

It looks like you are having an issue using OpenSeadragon, not the browser-extension. So you should ask your question [there](https://github.com/openseadragon/openseadragon/issues).

I would also recommend posting a link to what you did so far so that someone can help you.
