### ISSUE TITLE
Update to OSD 2.4.2

### ISSUE THREAD

**Issue by iangilman** [openseadragon/browser-extension#25]
We're already on 2.4.0 thanks to https://github.com/openseadragon/browser-extension/issues/20, and 2.4.1 is a fairly minor update (https://github.com/openseadragon/openseadragon/releases/tag/v2.4.1), so maybe we don't need to bother. At any rate, mentioning it here. I might need help from @avandecreme to do it all.

**Comment by iangilman** [comment]
Now it's time to do 2.4.2! Again, probably not a big deal, but still worth doing.

I think the thing I need help from @avandecreme on is actually publishing the new version of the extension.

**Comment by antoine-fl** [comment]
Hi @iangilman !

Thanks for taking care of that! Publishing the extension is unfortunately quite manual.
For Firefox, it can be done here: https://addons.mozilla.org/en-US/developers/addon/openseadragonizer/edit
For Chrome: https://chrome.google.com/webstore/developer/edit/lbjfeiidhldnfohmhnnnjgcmgjbnibgd?authuser=1#

Hopefully, the build instructions are up to date. I remember that the review process for Firefox is a bit cumbersome. In particular, they asked for the unminified source code of both the extension and its dependencies (OSD only in this case).

**Comment by avandecreme** [comment]
Hi @iangilman !

Thanks for taking care of that! Publishing the extension is unfortunately quite manual.
For Firefox, it can be done here: https://addons.mozilla.org/en-US/developers/addon/openseadragonizer/edit
For Chrome: https://chrome.google.com/webstore/developer/edit/lbjfeiidhldnfohmhnnnjgcmgjbnibgd?authuser=1#

Hopefully, the build instructions are up to date. I remember that the review process for Firefox is a bit cumbersome. In particular, they asked for the unminified source code of both the extension and its dependencies (OSD only in this case).

**Comment by iangilman** [comment]
@avandecreme Good to hear from you! Thank you for the guidance :) 

I've now upgraded the OSD in this repository and published it to openseadragon.github.io. I've also started the process for Chrome and Firefox (I'll update as I make progress).

I've also started a wiki page for the process: https://github.com/openseadragon/browser-extension/wiki/Distribution-Procedure

**Comment by avandecreme** [comment]
Thanks for doing that! Got the update on my Firefox install :+1:

**Comment by iangilman** [comment]
Excellent! The Chrome extension is up now as well. :)
