### ISSUE TITLE
Add to Chrome web store

### ISSUE THREAD

**Issue by iangilman** [openseadragon/browser-extension#3]
@avandecreme How do we go about that?

**Comment by avandecreme** [comment]
So we need to package the extension in a crx first:
https://developer.chrome.com/extensions/packaging

It involves creating a private key, so I am not sure where we can store it.
Maybe I can create it and share it with you privately?

After the first publication, it seems that we should be able to automate things: http://stackoverflow.com/questions/11822975/how-to-automate-publishing-chrome-extension-to-the-web-store

**Comment by iangilman** [comment]
Yes, that sounds reasonable. One way to share the private key would be via Dropbox or a similar service.

**Comment by avandecreme** [comment]
Published: https://chrome.google.com/webstore/detail/openseadragonizer/lbjfeiidhldnfohmhnnnjgcmgjbnibgd

We should add a screenshot however I am not sure what image to use for this. Any idea?
We can also post a video.

We can also add a detailed description up to 16000 words. I am not sure what we might want to write in there.

The next step is to automate the future releases.

**Comment by iangilman** [comment]
Awesome! 

Seems like it would be good to add a screenshot. I would say just an image with the OSD buttons in their usual position. Maybe if it's obvious that you're zoomed in to the image (i.e. things are cut off so it's clear you're just seeing a part of the image). As for which image to use, I suppose you could use the Duomo image from http://openseadragon.github.io.

I don't know that we need a terribly detailed description, but you should at least add instructions on how to operate it (i.e. use the right click menu). Also a link to the OpenSeadragon site would be good.

**Comment by iangilman** [comment]
When I add the extension from the Chrome store, it warns that it will be able to read my browser history. Do we need that capability? Can we turn it off so you don't get that warning?

**Comment by avandecreme** [comment]
>Seems like it would be good to add a screenshot. I would say just an image with the OSD buttons in their usual position. Maybe if it's obvious that you're zoomed in to the image (i.e. things are cut off so it's clear you're just seeing a part of the image). As for which image to use, I suppose you could use the Duomo image from http://openseadragon.github.io.

The thing is because Duomo is not an image but a pyramid, I can't open it with the plugin :D I might stitch it just for this purpose. I already have the code to do that.

>I don't know that we need a terribly detailed description, but you should at least add instructions on how to operate it (i.e. use the right click menu). Also a link to the OpenSeadragon site would be good. 

Good points.

>When I add the extension from the Chrome store, it warns that it will be able to read my browser history. Do we need that capability? Can we turn it off so you don't get that warning? 

I suppose it is because there is tabs in the manifest but we might be able to remove it: https://developer.chrome.com/extensions/tabs

**Comment by iangilman** [comment]
You could just take a snapshot of Duomo on the OpenSeadragon page...it doesn't have to be literally the browser extension. I suppose the one thing is adding the rotation buttons in; that page can easily be hacked for the purpose, or you could make your own page. Here is a tilesource definition for Duomo: 

https://github.com/openseadragon/openseadragon/blob/master/test/demo/m2/js/main.js#L728-L740

And let's try removing the tabs permission; might as well be as light on permissions as we can!

**Comment by avandecreme** [comment]
I think we got it all rolling.
Version 1.1.0 published.
